// Datos de los 42 equipos de fútbol español - LALIGA y LALIGA Hypermotion 2026-27
// escudoLocal: ruta a la carpeta imgescudos/ dentro del propio proyecto (debe subirse junto al resto de archivos)
// Los datos de palmarés son históricos y verificados; fundación/estadio son los más recientes conocidos.

const EQUIPOS = {

  // ===== PRIMERA DIVISIÓN =====
  "real-madrid": { nombre:"Real Madrid", division:"Primera", escudoLocal:"imgescudos/Real-madrid.png", fundacion:1902, ciudad:"Madrid", estadio:"Santiago Bernabéu", apodo:"Los Merengues", palmares:["Liga: 36 títulos","Copa del Rey: 20 títulos","Champions League: 15 títulos (récord europeo)"], noticia:"El Real Madrid afronta la 2026-27 como vigente aspirante a todos los títulos, con el objetivo de recuperar LaLiga tras la temporada pasada.", plantillaFecha:"16 de agosto de 2026", plantilla:[
    {d:1, n:"Thibaut Courtois", p:"Portero"},
    {d:13, n:"Andriy Lunin", p:"Portero"},
    {d:29, n:"Javier Navarro", p:"Portero"},
    {d:31, n:"Illia Voloshyn", p:"Portero"},
    {d:43, n:"Sergio Mestre", p:"Portero"},
    {d:3, n:"Éder Militão", p:"Defensa"},
    {d:12, n:"Trent Alexander-Arnold", p:"Defensa"},
    {d:16, n:"Ibrahima Konaté", p:"Defensa"},
    {d:17, n:"Marc Cucurella", p:"Defensa"},
    {d:17, n:"Raúl Asencio", p:"Defensa"},
    {d:18, n:"Álvaro Carreras", p:"Defensa"},
    {d:22, n:"Antonio Rüdiger", p:"Defensa"},
    {d:23, n:"Ferland Mendy", p:"Defensa"},
    {d:24, n:"Dean Huijsen", p:"Defensa"},
    {d:32, n:"Jesús Fortea", p:"Defensa"},
    {d:33, n:"Denzel Dumfries", p:"Defensa"},
    {d:5, n:"Jude Bellingham", p:"Centrocampista"},
    {d:6, n:"Eduardo Camavinga", p:"Centrocampista"},
    {d:8, n:"Fede Valverde", p:"Centrocampista"},
    {d:14, n:"Aurélien Tchouaméni", p:"Centrocampista"},
    {d:21, n:"Brahim Díaz", p:"Centrocampista"},
    {d:30, n:"Franco Mastantuono", p:"Centrocampista (cedido en la Fiorentina)"},
    {d:31, n:"Bernardo Silva", p:"Centrocampista"},
    {d:7, n:"Vinícius Júnior", p:"Delantero"},
    {d:10, n:"Kylian Mbappé", p:"Delantero"},
    {d:11, n:"Rodrygo", p:"Delantero"},
    {d:15, n:"Arda Güler", p:"Delantero"},
    {d:16, n:"Gonzalo García", p:"Delantero"},
    {d:25, n:"Yan Diomande", p:"Delantero"},
    {d:29, n:"Endrick", p:"Delantero"},
    {d:40, n:"Carlos Espí", p:"Delantero"}
  ] },
  "barcelona": { nombre:"FC Barcelona", division:"Primera", escudoLocal:"imgescudos/Barcelona.png", fundacion:1899, ciudad:"Barcelona", estadio:"Spotify Camp Nou", apodo:"Los Blaugrana", palmares:["Liga: 28 títulos","Copa del Rey: 32 títulos (récord)","Champions League: 5 títulos"], noticiasReales:[{titulo:"El Barça inicia la liga con goleada", resumen:"Manita en el Martínez Valero (0-5) con doblete de Raphinha y Fermín, y debut con asistencia de Anthony Gordon.", link:"barca-elche.html"}], noticia:"El Barça vuelve a jugar en el remodelado Spotify Camp Nou tras las obras de renovación, con Hansi Flick al frente del proyecto.", plantillaFecha:"16 de agosto de 2026", plantilla:[
    {d:"-", n:"Marc-André ter Stegen", p:"Portero"},
    {d:13, n:"Joan García", p:"Portero"},
    {d:25, n:"Wojciech Szczęsny", p:"Portero"},
    {d:40, n:"Áron Yaakobishvili", p:"Portero"},
    {d:88, n:"Iker Rodríguez", p:"Portero"},
    {d:3, n:"Alejandro Balde", p:"Defensa"},
    {d:4, n:"Ronald Araújo", p:"Defensa"},
    {d:5, n:"Pau Cubarsí", p:"Defensa"},
    {d:15, n:"Andreas Christensen", p:"Defensa"},
    {d:18, n:"Gerard Martín", p:"Defensa"},
    {d:23, n:"Jules Koundé", p:"Defensa"},
    {d:24, n:"Eric García", p:"Defensa"},
    {d:26, n:"Jofre Torrents", p:"Defensa"},
    {d:36, n:"Álvaro Cortés", p:"Defensa"},
    {d:6, n:"Gavi", p:"Centrocampista"},
    {d:16, n:"Fermín López", p:"Centrocampista"},
    {d:17, n:"Marc Casadó", p:"Centrocampista"},
    {d:20, n:"Dani Olmo", p:"Centrocampista"},
    {d:21, n:"Frenkie de Jong", p:"Centrocampista"},
    {d:22, n:"Marc Bernal", p:"Centrocampista"},
    {d:"-", n:"Anthony Gordon", p:"Delantero"},
    {d:7, n:"Karim Adeyemi", p:"Delantero"},
    {d:7, n:"Ferran Torres", p:"Delantero"},
    {d:8, n:"Pedri", p:"Delantero"},
    {d:10, n:"Lamine Yamal", p:"Delantero"},
    {d:11, n:"Raphinha", p:"Delantero"},
    {d:19, n:"Roony Bardghji", p:"Delantero"},
    {d:19, n:"Shane Kluivert", p:"Delantero"}
  ] },
  "atletico-madrid": { nombre:"Atlético de Madrid", division:"Primera", escudoLocal:"imgescudos/Atletico-de-madrid.png", fundacion:1903, ciudad:"Madrid", estadio:"Cívitas Metropolitano", apodo:"Los Colchoneros", palmares:["Liga: 11 títulos","Copa del Rey: 10 títulos","UEFA Europa League: 3 títulos"], noticiasReales:[{titulo:"El Atlético Fuencarral: La cárcel del talento", resumen:"Opinión: el culebrón de Julián Álvarez sigue activo y el club se niega a dejarle salir pese a las ofertas.", link:"atletico-fuencarral.html"}], noticia:"El Atlético busca pelear por LaLiga tras una temporada de transición, reforzando la plantilla en el mercado de verano.", plantillaFecha:"16 de agosto de 2026", plantilla:[
    {d:1, n:"Juan Musso", p:"Portero"},
    {d:13, n:"Jan Oblak", p:"Portero"},
    {d:31, n:"Salvador Esquivel", p:"Portero"},
    {d:2, n:"José María Giménez", p:"Defensa"},
    {d:3, n:"Matteo Ruggeri", p:"Defensa"},
    {d:16, n:"Nahuel Molina", p:"Defensa"},
    {d:17, n:"Dávid Hancko", p:"Defensa"},
    {d:18, n:"Marc Pubill", p:"Defensa"},
    {d:22, n:"Alejandro Grimaldo", p:"Defensa"},
    {d:24, n:"Robin Le Normand", p:"Defensa"},
    {d:30, n:"Dani Martínez", p:"Defensa"},
    {d:4, n:"Rodrigo Mendoza", p:"Centrocampista"},
    {d:5, n:"Johnny Cardoso", p:"Centrocampista"},
    {d:6, n:"Koke", p:"Centrocampista"},
    {d:8, n:"Pablo Barrios", p:"Centrocampista"},
    {d:10, n:"Álex Baena", p:"Centrocampista"},
    {d:11, n:"Thiago Almada", p:"Centrocampista"},
    {d:14, n:"Marcos Llorente", p:"Centrocampista"},
    {d:15, n:"Thomas Lemar", p:"Centrocampista"},
    {d:20, n:"Giuliano Simeone", p:"Centrocampista"},
    {d:23, n:"Morten Hjulmand", p:"Centrocampista"},
    {d:7, n:"Kang-In Lee", p:"Delantero"},
    {d:9, n:"Alexander Sørloth", p:"Delantero"},
    {d:12, n:"Carlos Martín", p:"Delantero"},
    {d:19, n:"Julián Álvarez", p:"Delantero"},
    {d:22, n:"Ademola Lookman", p:"Delantero"}
  ] },
  "athletic-club": { nombre:"Athletic Club", division:"Primera", escudoLocal:"imgescudos/Athletic-club.png", fundacion:1898, ciudad:"Bilbao", estadio:"San Mamés", apodo:"Los Leones", palmares:["Liga: 8 títulos","Copa del Rey: 23 títulos (2º máximo ganador)","Supercopa de España: 3 títulos"], noticia:"El Athletic afronta otra temporada con competición europea tras consolidarse en la zona alta de la tabla las últimas campañas.", plantillaFecha:"14 de agosto de 2026", plantilla:[
    {d:1, n:"Unai Simón", p:"Portero"},
    {d:26, n:"Mikel Santos", p:"Portero"},
    {d:27, n:"Álex Padilla", p:"Portero"},
    {d:2, n:"Andoni Gorosabel", p:"Defensa"},
    {d:3, n:"Dani Vivian", p:"Defensa"},
    {d:4, n:"Aitor Paredes", p:"Defensa"},
    {d:5, n:"Yeray Álvarez", p:"Defensa"},
    {d:12, n:"Jesús Areso", p:"Defensa"},
    {d:13, n:"Unai Eguíluz", p:"Defensa"},
    {d:14, n:"Aymeric Laporte", p:"Defensa"},
    {d:17, n:"Yuri Berchiche", p:"Defensa"},
    {d:19, n:"Adama Boiro", p:"Defensa"},
    {d:32, n:"Hugo Rincón", p:"Defensa"},
    {d:41, n:"Johaneko Louis-Jean", p:"Defensa"},
    {d:47, n:"Iker Monreal", p:"Defensa"},
    {d:8, n:"Oihan Sancet", p:"Centrocampista"},
    {d:16, n:"Íñigo Ruiz de Galarreta", p:"Centrocampista"},
    {d:18, n:"Mikel Jauregizar", p:"Centrocampista"},
    {d:23, n:"Robert Navarro", p:"Centrocampista"},
    {d:24, n:"Beñat Prados", p:"Centrocampista"},
    {d:28, n:"Peio Canales", p:"Centrocampista"},
    {d:29, n:"Beñat Gerenabarrena", p:"Centrocampista"},
    {d:30, n:"Alejandro Rego", p:"Centrocampista"},
    {d:44, n:"Selton Sánchez", p:"Centrocampista"},
    {d:"-", n:"Unai Vencedor", p:"Centrocampista"},
    {d:7, n:"Álex Berenguer", p:"Delantero"},
    {d:9, n:"Iñaki Williams", p:"Delantero"},
    {d:10, n:"Nico Williams", p:"Delantero"},
    {d:11, n:"Gorka Guruzeta", p:"Delantero"},
    {d:21, n:"Maroan Sannadi", p:"Delantero"},
    {d:22, n:"Nico Serrano", p:"Delantero"},
    {d:40, n:"Elijah Gift", p:"Delantero"},
    {d:49, n:"Álvaro Djaló", p:"Delantero"}
  ] },
  "real-sociedad": { nombre:"Real Sociedad", division:"Primera", escudoLocal:"imgescudos/Real-Sociedad.png", fundacion:1909, ciudad:"San Sebastián", estadio:"Reale Arena", apodo:"La Real", palmares:["Liga: 2 títulos (1980-81, 1981-82)","Copa del Rey: 3 títulos (1909, 1987, 2020)"], noticia:"La Real busca recuperar el nivel competitivo que la llevó a jugar Champions League hace unas temporadas." },
  "sevilla": { nombre:"Sevilla FC", division:"Primera", escudoLocal:"imgescudos/Sevilla.png", fundacion:1890, ciudad:"Sevilla", estadio:"Ramón Sánchez-Pizjuán", apodo:"Los Nervionenses", palmares:["Liga: 1 título (1945-46)","Copa del Rey: 5 títulos","UEFA Europa League: 7 títulos (récord absoluto)"], noticia:"El Sevilla, el equipo más laureado de la historia de la Europa League, trabaja para volver a la competición continental." },
  "real-betis": { nombre:"Real Betis", division:"Primera", escudoLocal:"imgescudos/Betis.png", fundacion:1907, ciudad:"Sevilla", estadio:"Benito Villamarín", apodo:"Los Verdiblancos", palmares:["Liga: 1 título (1934-35)","Copa del Rey: 3 títulos (1977, 2005, 2022)"], noticia:"El Betis consolida su proyecto europeo bajo la dirección de Manuel Pellegrini, aspirando a plaza continental de nuevo." },
  "villarreal": { nombre:"Villarreal CF", division:"Primera", escudoLocal:"imgescudos/Villarreal.png", fundacion:1923, ciudad:"Villarreal", estadio:"Estadio de la Cerámica", apodo:"El Submarino Amarillo", palmares:["UEFA Europa League: 1 título (2020-21)","Sin título de Liga ni Copa del Rey"], noticiasReales:[{titulo:"El Racing de Santander puntúa en liga 14 años después", resumen:"El Villarreal empató 2-2 en El Sardinero en la Jornada 1, en un partido loco con cuatro goles en la primera parte.", link:"racing-villarreal.html"}], noticia:"El Submarino Amarillo continúa su sólida trayectoria en la zona europea de la tabla, un habitual desde hace más de una década." },
  "valencia": { nombre:"Valencia CF", division:"Primera", escudoLocal:"imgescudos/Valencia.png", fundacion:1919, ciudad:"Valencia", estadio:"Mestalla", apodo:"Los Che", palmares:["Liga: 6 títulos","Copa del Rey: 8 títulos","Copa de la UEFA: 2 títulos"], noticia:"El Valencia busca estabilizarse en la zona media-alta tras varias temporadas complicadas en Mestalla." },
  "osasuna": { nombre:"CA Osasuna", division:"Primera", escudoLocal:"imgescudos/osasuna.png", fundacion:1920, ciudad:"Pamplona", estadio:"El Sadar", apodo:"Los Rojillos", palmares:["Sin títulos nacionales","Subcampeón de Copa del Rey en 2005"], noticia:"Osasuna afronta otra temporada apoyándose en su identidad de equipo combativo y en el ambiente de El Sadar." },
  "celta": { nombre:"RC Celta de Vigo", division:"Primera", escudoLocal:"imgescudos/Celta.png", fundacion:1923, ciudad:"Vigo", estadio:"Balaídos", apodo:"Los Célticos", palmares:["Sin títulos nacionales","Subcampeón de Copa del Rey en 1948 y 1994"], noticia:"El Celta busca consolidarse en Primera con una plantilla joven y un proyecto orientado al desarrollo de talento." },
  "rayo-vallecano": { nombre:"Rayo Vallecano", division:"Primera", escudoLocal:"imgescudos/Rayo-vallecano.png", fundacion:1924, ciudad:"Madrid", estadio:"Campo de Vallecas", apodo:"Los Franjirrojos", palmares:["Sin títulos nacionales"], noticia:"El Rayo continúa su racha de permanencias sólidas en Primera, con Vallecas como uno de los ambientes más pasionales de la Liga." },
  "espanyol": { nombre:"RCD Espanyol", division:"Primera", escudoLocal:"imgescudos/Espanyol.png", fundacion:1900, ciudad:"Barcelona", estadio:"RCDE Stadium", apodo:"Los Pericos", palmares:["Copa del Rey: 4 títulos (1929, 1940, 2000, 2006)"], noticia:"El Espanyol afronta su segunda temporada consecutiva en Primera tras el ascenso, buscando consolidarse en la categoría." },
  "getafe": { nombre:"Getafe CF", division:"Primera", escudoLocal:"imgescudos/Getafe.png", fundacion:1946, ciudad:"Getafe", estadio:"Coliseum", apodo:"Los Azulones", palmares:["Sin títulos nacionales"], noticia:"El Getafe mantiene su estilo combativo bajo la dirección de José Bordalás, un habitual de la mitad de tabla." },
  "levante": { nombre:"Levante UD", division:"Primera", escudoLocal:"imgescudos/Levante.png", fundacion:1909, ciudad:"Valencia", estadio:"Ciutat de València", apodo:"Los Granotas", palmares:["Sin títulos nacionales"], noticia:"El Levante regresa a Primera con el objetivo de asentarse en la categoría tras su ascenso." },
  "elche": { nombre:"Elche CF", division:"Primera", escudoLocal:"imgescudos/Elche.png", fundacion:1923, ciudad:"Elche", estadio:"Manuel Martínez Valero", apodo:"Los Franjiverdes", palmares:["Sin títulos nacionales","Subcampeón de Copa del Rey en 1969"], noticiasReales:[{titulo:"El Barça inicia la liga con goleada", resumen:"El Elche cayó 0-5 en casa ante el FC Barcelona en su debut liguero, con doblete de Raphinha y Fermín.", link:"barca-elche.html"}], noticia:"El Elche vuelve a la máxima categoría con la ilusión de un club histórico que regresa tras años en Segunda." },
  "alaves": { nombre:"Deportivo Alavés", division:"Primera", escudoLocal:"imgescudos/Alaves.png", fundacion:1921, ciudad:"Vitoria-Gasteiz", estadio:"Mendizorrotza", apodo:"Los Babazorros", palmares:["Sin títulos nacionales","Subcampeón de Copa del Rey y de la Recopa de Europa en 2001"], noticia:"El Alavés continúa su etapa de estabilidad en Primera, siendo uno de los clubes más sólidos de la categoría en la última década." },
  "malaga": { nombre:"Málaga CF", division:"Primera", escudoLocal:"imgescudos/Malaga.png", fundacion:1948, ciudad:"Málaga", estadio:"La Rosaleda", apodo:"Los Boquerones", palmares:["Sin títulos nacionales"], noticia:"El Málaga regresa a Primera División tras varias temporadas en categorías inferiores, un ascenso histórico para su afición." },
  "racing-santander": { nombre:"Real Racing Club de Santander", division:"Primera", escudoLocal:"imgescudos/Racing-santander.png", fundacion:1913, ciudad:"Santander", estadio:"El Sardinero", apodo:"Los Racinguistas", palmares:["Subcampeón de Primera División en 1930-31","Campeón de Segunda División (2): 1949-50, 1959-60","Campeón de Primera División RFEF en 2021-22","Campeón de Segunda División B (4): 1990-91, 2013-14, 2015-16, 2018-19"], noticiasReales:[{titulo:"El Racing de Santander puntúa en liga 14 años después", resumen:"Debut en El Sardinero 14 años después, con empate 2-2 ante el Villarreal en un partido loco de cuatro goles en la primera parte.", link:"racing-villarreal.html"}], noticia:"El Racing regresa a Primera tras 14 años de ausencia, coronado campeón de LALIGA Hypermotion 2025-26." },
  "deportivo": { nombre:"RC Deportivo de La Coruña", division:"Primera", escudoLocal:"imgescudos/Deportivo.png", fundacion:1906, ciudad:"A Coruña", estadio:"Riazor", apodo:"Los Súper Depor", palmares:["Liga: 1 título (1999-2000)","Copa del Rey: 2 títulos (1995, 2002)"], noticia:"El Deportivo vuelve a Primera tras años de travesía por el fútbol modesto, recuperando el nombre del histórico 'Súper Depor'." },

  // ===== SEGUNDA DIVISIÓN (LALIGA HYPERMOTION) =====
  "girona": { nombre:"Girona FC", division:"Segunda", escudoLocal:"imgescudos/Girona.png", fundacion:1930, ciudad:"Girona", estadio:"Montilivi", apodo:"Los Blanc-i-vermells", palmares:["Sin títulos nacionales","Mejor puesto histórico: 3º en Primera División (2023-24), clasificación a Champions League"], noticia:"El Girona afronta la reconstrucción en Segunda tras el descenso, con el objetivo de un rápido regreso a Primera." },
  "mallorca": { nombre:"RCD Mallorca", division:"Segunda", escudoLocal:"imgescudos/Mallorca.png", fundacion:1916, ciudad:"Palma", estadio:"Son Moix", apodo:"Los Bermellones", palmares:["Copa del Rey: 1 título (2002-03)","Subcampeón de Copa del Rey en 1991 y 1998"], noticia:"El Mallorca busca el ascenso inmediato tras el descenso, apoyándose en la fortaleza que mostró en Son Moix durante años en Primera." },
  "oviedo": { nombre:"Real Oviedo", division:"Segunda", escudoLocal:"imgescudos/Real-oviedo.png", fundacion:1926, ciudad:"Oviedo", estadio:"Carlos Tartiere", apodo:"Los Carbayones", palmares:["Sin títulos nacionales"], noticia:"El Oviedo regresa a Segunda tras una sola temporada en Primera, con el reto de no repetir el patrón de ascensor." },
  "tenerife": { nombre:"CD Tenerife", division:"Segunda", escudoLocal:"imgescudos/tenerife.png", fundacion:1922, ciudad:"Santa Cruz de Tenerife", estadio:"Heliodoro Rodríguez López", apodo:"Los Chicharreros", palmares:["Sin títulos nacionales"], noticia:"El Tenerife regresa a Segunda tras ascender de forma directa desde Primera Federación, sumando ilusión a su histórico Heliodoro." },
  "sabadell": { nombre:"CE Sabadell FC", division:"Segunda", escudoLocal:"imgescudos/sabadell.png", fundacion:1912, ciudad:"Sabadell", estadio:"Nova Creu Alta", apodo:"Los Arlequinats", palmares:["Sin títulos nacionales"], noticia:"El Sabadell da el salto al fútbol profesional tras ascender vía playoff desde Primera Federación, su gran hito histórico reciente." },
  "eldense": { nombre:"CD Eldense", division:"Segunda", escudoLocal:"imgescudos/eldense.png", fundacion:1922, ciudad:"Elda", estadio:"Nuevo Pepico Amat", apodo:"Los Azulgrana de Elda", palmares:["Sin títulos nacionales"], noticia:"El Eldense vive su primera temporada en Segunda División de su historia tras un ascenso directo histórico desde Primera Federación." },
  "celta-fortuna": { nombre:"RC Celta Fortuna", division:"Segunda", escudoLocal:"imgescudos/Celta.png", fundacion:2019, ciudad:"Vigo", estadio:"A Madroa", apodo:"El Fortuna", palmares:["Sin títulos; filial del RC Celta de Vigo"], noticia:"El filial del Celta debuta en Segunda División tras ascender vía playoff, un hito histórico para la cantera céltica." },
  "cadiz": { nombre:"Cádiz CF", division:"Segunda", escudoLocal:"imgescudos/Cadiz.png", fundacion:1910, ciudad:"Cádiz", estadio:"Nuevo Mirandilla", apodo:"El Submarino Amarillo (histórico)", palmares:["Sin títulos nacionales"], noticia:"El Cádiz busca recuperar la categoría tras varias temporadas de dificultades en Segunda." },
  "cordoba": { nombre:"Córdoba CF", division:"Segunda", escudoLocal:"imgescudos/Cordoba.png", fundacion:1954, ciudad:"Córdoba", estadio:"Nuevo Arcángel", apodo:"Los Califas", palmares:["Sin títulos nacionales"], noticia:"El Córdoba continúa su proceso de recuperación tras años en categorías inferiores del fútbol español." },
  "granada": { nombre:"Granada CF", division:"Segunda", escudoLocal:"imgescudos/Granada.png", fundacion:1931, ciudad:"Granada", estadio:"Nuevo Los Cármenes", apodo:"Los Nazaríes", palmares:["Sin títulos nacionales"], noticia:"El Granada busca el regreso a Primera tras el descenso, apoyándose en el ambiente de Los Cármenes." },
  "las-palmas": { nombre:"UD Las Palmas", division:"Segunda", escudoLocal:"imgescudos/Las-palmas.png", fundacion:1949, ciudad:"Las Palmas de Gran Canaria", estadio:"Estadio de Gran Canaria", apodo:"Los Amarillos", palmares:["Sin títulos nacionales","Subcampeón de Copa del Rey en 1978"], noticia:"La UD Las Palmas busca el ascenso inmediato tras el descenso, con el respaldo de una de las aficiones más numerosas de la categoría." },
  "almeria": { nombre:"UD Almería", division:"Segunda", escudoLocal:"imgescudos/UD-Almería.png", fundacion:1989, ciudad:"Almería", estadio:"Power Horse Stadium", apodo:"Los Indálicos", palmares:["Sin títulos nacionales"], noticia:"El Almería continúa su proyecto de reconstrucción tras varios años alternando entre Primera y Segunda." },
  "albacete": { nombre:"UD Albacete Balompié", division:"Segunda", escudoLocal:"imgescudos/Albacete.png", fundacion:1940, ciudad:"Albacete", estadio:"Carlos Belmonte", apodo:"Los Queseros", palmares:["Sin títulos nacionales"], noticia:"El Albacete continúa asentado en Segunda, siendo uno de los históricos habituales de la categoría de plata." },
  "eibar": { nombre:"SD Eibar", division:"Segunda", escudoLocal:"imgescudos/Eibar.png", fundacion:1940, ciudad:"Eibar", estadio:"Ipurua", apodo:"Los Armeros", palmares:["Sin títulos nacionales"], noticia:"El Eibar mantiene su modelo de club modesto y bien gestionado, referencia de estabilidad en Segunda División." },
  "sporting": { nombre:"Real Sporting de Gijón", division:"Segunda", escudoLocal:"imgescudos/Real-sporting.png", fundacion:1905, ciudad:"Gijón", estadio:"El Molinón", apodo:"Los Rojiblancos", palmares:["Sin títulos nacionales","Subcampeón de Liga en 1978-79"], noticia:"El Sporting busca el ascenso a Primera, categoría de la que lleva ausente desde 2017, apoyado en la afición de El Molinón." },
  "valladolid": { nombre:"Real Valladolid CF", division:"Segunda", escudoLocal:"imgescudos/Valladolid.png", fundacion:1928, ciudad:"Valladolid", estadio:"José Zorrilla", apodo:"Los Pucelanos", palmares:["Sin títulos nacionales"], noticia:"El Valladolid busca recuperar la categoría tras el descenso, con José Zorrilla como uno de los estadios más entregados de Segunda." },
  "burgos": { nombre:"Burgos CF", division:"Segunda", escudoLocal:"imgescudos/Burgos.png", fundacion:1994, ciudad:"Burgos", estadio:"El Plantío", apodo:"Los Blanquinegros", palmares:["Sin títulos nacionales"], noticia:"El Burgos CF sigue consolidándose en Segunda, categoría a la que llegó tras un notable ascenso desde Primera RFEF." },
  "castellon": { nombre:"CD Castellón", division:"Segunda", escudoLocal:"imgescudos/Castellon.png", fundacion:1922, ciudad:"Castellón de la Plana", estadio:"Castalia", apodo:"Los Orelluts", palmares:["Sin títulos nacionales"], noticia:"El Castellón continúa su proyecto de crecimiento en Segunda tras su regreso al fútbol profesional." },
  "leganes": { nombre:"CD Leganés", division:"Segunda", escudoLocal:"imgescudos/Leganes.png", fundacion:1928, ciudad:"Leganés", estadio:"Butarque", apodo:"Los Pepineros", palmares:["Sin títulos nacionales"], noticia:"El Leganés regresa a Segunda tras el descenso, buscando de nuevo el ascenso a la máxima categoría." },
  "andorra": { nombre:"FC Andorra", division:"Segunda", escudoLocal:"imgescudos/Andorra.png", fundacion:1942, ciudad:"Andorra la Vella", estadio:"Estadi Nacional", apodo:"Los Tricolors", palmares:["Sin títulos nacionales"], noticia:"El FC Andorra continúa su proyecto de crecimiento, siendo el único club de Segunda con sede fuera de España." },
  "ceuta": { nombre:"AD Ceuta FC", division:"Segunda", escudoLocal:"imgescudos/Ceuta.png", fundacion:1956, ciudad:"Ceuta", estadio:"Alfonso Murube", apodo:"Los Caballas", palmares:["Sin títulos nacionales","Primer ascenso histórico a Segunda División en 2024"], noticia:"El Ceuta continúa haciendo historia como el primer equipo de la ciudad autónoma en jugar en la categoría de plata." },
  "real-sociedad-b": { nombre:"Real Sociedad B", division:"Segunda", escudoLocal:"imgescudos/Real-sociedad-b.png", fundacion:1962, ciudad:"San Sebastián", estadio:"Zubieta", apodo:"El Sanse", palmares:["Filial del club; no elegible para títulos nacionales de Liga"], noticia:"El Sanse afronta su primera temporada en Segunda como escaparate de la cantera de la Real Sociedad." },

};
